source 'http://rubygems.org'
ruby "1.9.3"

gem 'rails', '3.2.6' #this is a comment, too. 
gem 'jquery-rails' # this is a comment
gem 'execjs', '< 1.4.0'
gem 'therubyracer', '> 0.10.1'
gem 'will_paginate', '<= 3.0.3'
gem 'gravatar_image_tag', '>=1.1.3'
# gem 'tire'

group :assets do
  gem 'sassy', "~> 3.2.0"
  gem 'sass-rails', "~> 3.2"
end

gem 'cucumber-rails', require: false
gem 'fastercsv', :require => false
gem "guard-livereload", :group => :development, :require => false
gem "copycopter_client", :git => "git://github.com/nmk/copycopter-ruby-client.git"
gem 'govkit', :path => "#{File.expand_path(__FILE__)}/../vendor/gems"

gemspec 